name: salma_love
description: A special app for Salma
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/unnamed.jpg
    - "img/game (1).jpeg"
    - "img/game (2).jpeg"
    - "img/game (3).jpeg"
    - "img/game (4).jpeg"
    - "img/game (5).jpeg"
    - "img/game (6).jpeg"
    - "img/game (7).jpeg"