name: salma_love
description: A special app for Salma
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.0.0
  provider: ^6.1.0
  url_launcher: ^6.2.0
  uuid: ^4.0.0
  in_app_purchase: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/unnamed.jpg
    - "img/game (1).jpeg"
    - "img/game (2).jpeg"
    - "img/game (3).jpeg"
    - "img/game (4).jpeg"
    - "img/game (5).jpeg"
    - "img/game (6).jpeg"
    - "img/game (7).jpeg"